name: Docker Image CI

on:
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]
  workflow_dispatch:
  push:
    tags:
      - '*.*.*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set output
      id: vars
      run: echo "LATEST_TAG=$(git fetch --all --tags && git describe --tags `git rev-list --tags --max-count=1`)" >> $GITHUB_ENV
      shell: bash

    - name: Check output
      env:
        RELEASE_VERSION: ${{ env.LATEST_TAG }}
      run: |
        echo $RELEASE_VERSION
        echo ${{ env.LATEST_TAG}}
        echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
        echo "Tag name from github.ref_name: ${{  github.ref_name }}"
        echo "$(git describe --tags `git rev-list --tags --max-count=1`)"

    - name: Show work directory
      run: ls -lha

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Show work directory
      run: ls -lha
      
    - name: Build and push ${{ env.LATEST_TAG}}
      uses: docker/build-push-action@v4
      with:
        context: "{{defaultContext}}:tutorial"
        push: true
        tags: stribogp/snippets:${{ env.LATEST_TAG}}

    - name: Build and push latest
      uses: docker/build-push-action@v4
      with:
        context: "{{defaultContext}}:tutorial"
        push: true
        tags: stribogp/snippets:${{ env.LATEST_TAG}}

    - name: Deploy
      uses: WyriHaximus/github-action-helm3@v3
      with:
        exec: helm upgrade test-app ./helm/app/ --install --wait --atomic --namespace=demo-pavel --values=./helm/app/values.yaml --set image.tag=${{ env.LATEST_TAG}}
        kubeconfig: '${{ secrets.KUBECONFIG }}'
        overrule_existing_kubeconfig: "true"
