name: Delete test-app

on:
  workflow_dispatch:


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Deploy
      uses: WyriHaximus/github-action-helm3@v3
      with:
        exec: helm delete test-app
        kubeconfig: '${{ secrets.KUBECONFIG }}'
        overrule_existing_kubeconfig: "true"
